### PR TITLE
#383 fix bug with editing message and refreshing the page

### PR DESCRIPTION
**Pull request by JorisBassle**
uhuru Beta V1.2

### CODE REVIEW

**Comment by EdwardKerckhof** [comment]
Looks good to me. Will wait until @JensMeire has reviewed and when V1.1 is fully done.

**Review by EdwardKerckhof — APPROVED** [review]
Looks good to me. Will wait until @JensMeire has reviewed and when V1.1 is fully done.

**Comment by JensMeire** [comment]
Resolve conflicts @JorisBassle

**Review by JensMeire — APPROVED** [review]

**Comment by JensMeire** [comment]
@JorisBassle Still needs merge conflicts

**Comment by JorisBassle** [comment]
@JensMeire resolved conflicts

**Pull request merged**
